title: TRELIS Toolkit
description: Open-access curriculum for training and retaining leaders in STEM
show_downloads: true
google_analytics:
theme: jekyll-theme-slate

header_pages:
 #- index.md
 - another-page.md
